MARKETPLACE_SHOP   = (!defined?(MARKETPLACE_MODE_ONLINE_SHOP) or (MARKETPLACE_MODE_ONLINE_SHOP == true))
MARKETPLACE_RETAIL = (defined?(MARKETPLACE_MODE_ONLINE_SHOP) && (MARKETPLACE_MODE_ONLINE_SHOP != true) && defined?(MARKETPLACE_MODE_RETAIL) && (MARKETPLACE_MODE_RETAIL == true))
MARKETPLACE_FULL   = (defined?(MARKETPLACE_MODE_ONLINE_SHOP) && (MARKETPLACE_MODE_ONLINE_SHOP != true) && (!defined?(MARKETPLACE_MODE_RETAIL) or (MARKETPLACE_MODE_RETAIL != true)))

require 'marketplace_general'
require 'marketplace_retail'
require 'marketplace_full'
