GOOGLE_RECAPTCHA_API_KEY_PUB = '6LcH'
GOOGLE_RECAPTCHA_API_KEY_SECRET = '6Lm'

## =================================================================
## ============= SEED and SALT must be unique per site =============
SAFE_UID_SEED_CART_ITEM = 0x11111111
SAFE_UID_SEED_CUSTOMER = 0x11111111
SAFE_UID_SEED_ORDER_ITEM = 0x11111111
SAFE_UID_SEED_ORDER_PRODUCT_LIST = 0x11111111
SAFE_UID_SEED_ORDER_PAY_SERVICE = 0x11111111
SAFE_UID_SEED_PAYINVOICE_ITEM = 0x11111111
SAFE_UID_SEED_PAYINVOICE_PAY_SERVICE = 0x11111111
SAFE_UID_SEED_PAYMENT_ITEM = 0x11111111
SAFE_UID_SEED_PAYMENT_SVC_METHOD = 0x11111111
SAFE_UID_SEED_OTHER_DOCS = 0x11111111
SAFE_UID_SEED_SELLER_PRODUCT = 0x11111111
SAFE_UID_SEED_SELLER_SUPPLIER = 0x11111111
SAFE_UID_SEED_USER = 0x11111111
SAFE_UID_SEED_ACL_SID = 0x11111111
SAFE_UID_SEED_FRONTEND_VAR = 0x11111111
SAFE_UID_SEED_FRONTEND_CONFIRM = 0x11111111

SAFE_UID_SALT_CUSTOMER = 'asd'
SAFE_UID_SALT_ORDER_ITEM = 'asd'
SAFE_UID_SALT_ORDER_PRODUCT_LIST = 'asd'
SAFE_UID_SALT_ORDER_PAY_SERVICE = 'asd'
SAFE_UID_SALT_PAYINVOICE_ITEM = 'asd'
SAFE_UID_SALT_PAYINVOICE_PAY_SERVICE = 'asd'
SAFE_UID_SALT_PAYMENT_ITEM = 'asd'
SAFE_UID_SALT_OTHER_DOCS = 'asd'
SAFE_UID_SALT_USER = 'asd'
SAFE_UID_SALT_SELLER_SUPPLIER = 'asd'
SAFE_UID_SALT_ACL_SID = 'asdasdasd'
SAFE_UID_SALT_FRONTEND_CONFIRM = 'asdasdas'

SAFE_FORM_SALT_PAYMENTS = 'asda'
SAFE_FORM_SALT_PRODUCTS = 'asda'
SAFE_FORM_SEED_IMPORT_SUPPLIER = 0x11111111
## =================================================================


DOC_TYPE_SOME_DOC = 1
DOC_TYPE_ORDER = 2
DOC_TYPE_PAY_INVOICE = 3
DOC_TYPE_AKT_WORK = 4
DOC_TYPE_AKT_REFUND = 5

DOCUMENT_TYPES = {
	DOC_TYPE_SOME_DOC => {l: 'D', salt: SAFE_UID_SALT_OTHER_DOCS, salt_paysvc: nil, seed: SAFE_UID_SEED_OTHER_DOCS, seed_paysvc: nil},
	DOC_TYPE_ORDER => {l: 'E', salt: SAFE_UID_SALT_ORDER_ITEM, salt_paysvc: SAFE_UID_SALT_ORDER_PAY_SERVICE, seed: SAFE_UID_SEED_ORDER_ITEM, seed_paysvc: SAFE_UID_SEED_ORDER_PAY_SERVICE},
	DOC_TYPE_PAY_INVOICE => {l: 'P', salt: SAFE_UID_SALT_PAYINVOICE_ITEM, salt_paysvc: SAFE_UID_SALT_PAYINVOICE_PAY_SERVICE, seed: SAFE_UID_SEED_PAYINVOICE_ITEM, seed_paysvc: SAFE_UID_SEED_PAYINVOICE_PAY_SERVICE},
	DOC_TYPE_AKT_WORK => {l: 'A', salt: SAFE_UID_SALT_OTHER_DOCS, salt_paysvc: nil, seed: SAFE_UID_SEED_OTHER_DOCS, seed_paysvc: nil},
	DOC_TYPE_AKT_REFUND => {l: 'F', salt: SAFE_UID_SALT_OTHER_DOCS, salt_paysvc: nil, seed: SAFE_UID_SEED_OTHER_DOCS, seed_paysvc: nil},
}